#!/bin/bash

alexei@pad:~$ cat>f1.txt
1
a
2
b
c^Z
[11]+  Остановлен    cat > f1.txt     
[12]+  Остановлен    cat > f2.txt
alexei@pad:~$ cat>f2.txt
1
a
2
b
c
^Z
[13]+  Остановлен    cat > f2.txt
alexei@pad:~$ cmp -b f1.txt f2.txt
cmp: EOF в f1.txt после байта 8, строка 4
alexei@pad:~$ cat>f3.txt
аёу   
4
аёу 0
^Z
[14]+  Остановлен    cat > f3.txt
alexei@pad:~$ cat>f5.txt
as
1
bin
util
^Z
[9]+  Остановлен    cat > f5.txt
alexei@pad:~$ tr -d a-z <f5.txt

1


alexei@pad:~$ cut -b 1 f1.txt
1
a
2
b
alexei@pad:~$ du -ach
....
24K	./etc
4,0K	./lab.c
4,0K	./lab14.c~
0	./#lab13.c#
4,0K	./laba.lab
4,0K	./#lab8.c#
12K	./12lab
1002M	.
1002M	итого
alexei@pad:~$ join f1.txt f2.txt
1
a
2
b
14 14 итого
alexei@pad:~$ diff f1.txt f2.txt
4a5
> c
alexei@pad:~$ grep -w "аёу" f3.txt
аёу 
аёу 0
alexei@pad:~$ grep -v "a" f1.txt
1
2
b
alexei@pad:~$ grep -c "a" f1.txt
1
alexei@pad:~$ grep -l "a" f1.txt f2.txt f3.txt
f1.txt
f2.txt
f3.txt

alexei@pad:~$ wc -l f1.txt
4 f1.txt
alexei@pad:~$ wc -c f1.txt
8 f1.txt
alexei@pad:~$ wc -m f1.txt
8 f1.txt
alexei@pad:~$ wc -L f1.txt
1 f1.txt
alexei@pad:~$ wc -w f1.txt
4 f1.txt
alexei@pad:~$ wc -lw f1.txt f2.txt f3.txt
 4  4 f1.txt
 5  5 f2.txt
 3  4 f3.txt
12 13 итого
alexei@pad:~$ cat>f4.txt
don
^Z
[7]+  Остановлен    cat > f4.txt
alexei@pad:~$ dd if=f1.txt of=f4.txt
0+1 записей получено
0+1 записей отправлено
8 bytes copied, 0,00103144 s, 7,8 kB/s
alexei@pad:~$ cat f4.txt
1
a
2
b

alexei@pad:~$ tail -3 f1.txt
a
2
b
alexei@pad:~$ paste -s f5.txt
as	1	bin	util
alexei@pad:~$ echo "ogurchik" | dd cbs=1 conv=unblock 2> /dev/null
o
g
u
r
c
h
i
k

alexei@pad:~$ df -k
Файл.система   1K-блоков Использовано  Доступно Использовано% Cмонтировано в
udev             1914712            0   1914712            0% /dev
tmpfs             388992         1896    387096            1% /run
/dev/sda8      190643124     10945948 169943372            7% /
tmpfs            1944956        56844   1888112            3% /dev/shm
tmpfs               5120            4      5116            1% /run/lock
tmpfs            1944956            0   1944956            0% /sys/fs/cgroup
/dev/loop6         13312        13312         0          100% /snap/gnome-characters/103
/dev/loop1         14848        14848         0          100% /snap/gnome-logs/37
/dev/loop0        144128       144128         0          100% /snap/gnome-3-26-1604/78
/dev/loop2         93184        93184         0          100% /snap/core/6405
/dev/loop3          2432         2432         0          100% /snap/gnome-calculator/180
/dev/loop4          3840         3840         0          100% /snap/gnome-system-monitor/51
/dev/loop5          2304         2304         0          100% /snap/gnome-calculator/260
/dev/loop7         93184        93184         0          100% /snap/core/6350
/dev/loop9         35456        35456         0          100% /snap/gtk-common-themes/818
/dev/loop11        13312        13312         0          100% /snap/gnome-characters/139
/dev/loop10        14976        14976         0          100% /snap/gnome-logs/45
/dev/loop8        144128       144128         0          100% /snap/gnome-3-26-1604/74
/dev/loop18         3840         3840         0          100% /snap/gnome-system-monitor/57
/dev/loop13         2304         2304         0          100% /snap/gnome-calculator/238
/dev/loop12        35712        35712         0          100% /snap/gtk-common-themes/1122
/dev/loop14       144128       144128         0          100% /snap/gnome-3-26-1604/82
/dev/loop15        36224        36224         0          100% /snap/gtk-common-themes/1198
/dev/loop16        91648        91648         0          100% /snap/core/6130
/dev/loop17        14848        14848         0          100% /snap/gnome-logs/43
/dev/loop19        13312        13312         0          100% /snap/gnome-characters/124
/dev/sda1         262144        32964    229180           13% /boot/efi
tmpfs             388988           16    388972            1% /run/user/121
tmpfs             388988           44    388944            1% /run/user/1000
alexei@pad:~$ sum f2.txt
31949     1
alexei@pad:~$ tee -a f2.txt
dron
dron
3l3ktron
3l3ktron
^Z
[16]+  Остановлен    tee -a f2.txt
alexei@pad:~$ cat f2.txt
1
a
2
b
c
dron
3l3ktron
